### ISSUE TITLE
Issue with authorized_sessionmaker

### ISSUE THREAD

**Issue by rshayesteh** [osohq/fastapi-sqlalchemy-okta-oso-example#2]
The `authorized_sessionmaker` seems to have issues with `get_action` parameter and throws the following error: 
    action = checked_permissions.get(entity)
AttributeError: 'str' object has no attribute 'get'

Am I doing something wrong?

**Comment by samscott89** [comment]
Hey @rshayesteh 

This repository is a little out of date, you can see a more up-to-date example of using sqlalchemy-oso at [osohq/gitclub](https://github.com/osohq/gitclub/tree/main/backends/flask-sqlalchemy-oso)

And the documentation for using the checked_permissions attribute is [here](https://docs.osohq.com/reference/frameworks/data_filtering/sqlalchemy.html#authorizing-a-users-posts)

**Comment by rshayesteh** [comment]
Thanks for the reply @samscott89 
I will try those links!
